/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import static helper.HelperPreencherTabelas.preencherTabelaAgenciaEditarConta;
import static helper.HelperPreencherTabelas.preencherTabelaClienteEditarConta;
import static helper.HelperPreencherTabelas.preencherEditarCliente;
import static helper.HelperPreencherTabelas.preencherEditarConta;
import static helper.HelperPreencherTabelas.preencherEditarAgencia;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ytalo
 */
public class SubMenuEditarView extends javax.swing.JFrame {

    private EditarCliente editarCliente;
    private EditarConta editarConta;
    private EditarAgencia editarAgencia;

    /**
     * Creates new form SubMenuEditarView
     */
    public SubMenuEditarView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();
        btnEditarAgencia = new javax.swing.JButton();
        btnEditarConta = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Editar");

        btnSair.setBackground(new java.awt.Color(255, 0, 0));
        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnEditarCliente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEditarCliente.setText("Atualizar Cliente");
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });

        btnEditarAgencia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEditarAgencia.setText("Atualizar Agência");
        btnEditarAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAgenciaActionPerformed(evt);
            }
        });

        btnEditarConta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEditarConta.setText("Atualizar Conta");
        btnEditarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarContaActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar_cliente.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar_conta.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar_agencia.png"))); // NOI18N

        btnVoltar.setBackground(new java.awt.Color(51, 51, 255));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnEditarCliente)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnEditarConta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEditarAgencia)
                        .addGap(31, 31, 31)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnVoltar))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:

        int opcao = JOptionPane.showConfirmDialog(this, "Deseja sair?");
        if (opcao == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        // TODO add your handling code here:

        if (editarCliente == null) {
            editarCliente = new EditarCliente();

        }
        editarCliente.setLocationRelativeTo(null);
        editarCliente.setVisible(true);

        try {
            preencherEditarCliente();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível carregar a tabela.");
        }

    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void btnEditarAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAgenciaActionPerformed
        // TODO add your handling code here:

        if (editarAgencia == null) {
            editarAgencia = new EditarAgencia();

        }
        editarAgencia.setLocationRelativeTo(null);
        editarAgencia.setVisible(true);

        try {

            preencherEditarAgencia();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível carregar a tabela.");
        }
    }//GEN-LAST:event_btnEditarAgenciaActionPerformed

    private void btnEditarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarContaActionPerformed
        // TODO add your handling code here:

        if (editarConta == null) {
            editarConta = new EditarConta();

        }
        editarConta.setLocationRelativeTo(null);
        editarConta.setVisible(true);

        try {
            preencherEditarConta();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Não foi possível carregar a tabela.");
        }

        try {
            preencherTabelaAgenciaEditarConta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível carregar a tabela.");
        }

        try {
            preencherTabelaClienteEditarConta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível carregar a tabela.");
        }
    }//GEN-LAST:event_btnEditarContaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubMenuEditarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubMenuEditarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubMenuEditarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubMenuEditarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubMenuEditarView().setVisible(true);
            }
        });
    }

    /*public static void preencherTabelaAgencia() throws SQLException {

        DefaultTableModel model = (DefaultTableModel) tblTabelaAgencia.getModel();
        model.setNumRows(0);

        Object colunas[] = new Object[5];
        Agencia agencia = new Agencia();

        ArrayList<Agencia> listaAgencias = new ArrayList<Agencia>();

        listaAgencias = AgenciaDAOView.listarAgencias();

        for (int i = 0; i < listaAgencias.size(); i++) {

            agencia = listaAgencias.get(i);
            colunas[0] = agencia.getId_agencia();
            colunas[1] = agencia.getNumero();
            colunas[2] = agencia.getGerente();
            colunas[3] = agencia.getLocalizacao();
            colunas[4] = agencia.getTelefone();

            model.addRow(colunas);
        }
    }
   
    public static void preencherTabelaCliente() throws SQLException {

        DefaultTableModel model = (DefaultTableModel) tblTabelaCliente.getModel();
        model.setNumRows(0);

        Object colunas[] = new Object[3];
        Cliente cliente = new Cliente();

        ArrayList<Cliente> listaClientes = new ArrayList<Cliente>();

        listaClientes = ClienteDAOView.listarClientes();

        for (int i = 0; i < listaClientes.size(); i++) {

            cliente = listaClientes.get(i);
            colunas[0] = cliente.getNome();
            colunas[1] = cliente.getCpf();
            colunas[2] = cliente.getContato();

            model.addRow(colunas);
        }
    }
    
        public static void preencherTabelaConta() throws SQLException {

        DefaultTableModel model = (DefaultTableModel) tblTabelaConta.getModel();
        model.setNumRows(0);

        Object colunas[] = new Object[5];
        Conta conta = new ContaCorrente();

        ArrayList<Conta> listaContas = new ArrayList<Conta>();

        listaContas = ContaDAOView.listarContas();

        for (int i = 0; i < listaContas.size(); i++) {

            conta = listaContas.get(i);
            colunas[0] = conta.getTitular();
            colunas[1] = conta.getNumeroConta();
            colunas[2] = conta.getTipoConta();
            colunas[3] = conta.getSaldo();
            colunas[4] = conta.getAgencia();

            model.addRow(colunas);
        }
    }
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarAgencia;
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnEditarConta;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
